---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: webmaster@<example.com>
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable HTTP01 validations
    http01: {}
