---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  creationTimestamp: null
  generation: 1
  labels:
    app: kibana
  name: kibana
spec:
  rules:
  - host: logs.<example.com>
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 443
        path: /
  - host: logs.labs.<example.com>
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 443
        path: /
  tls:
  - hosts:
    - logs.<example.com>
    secretName: kibana-tls-prod
status:
  loadBalancer: {}